qualcomm-qca9377: fix LICENSE
I2SE/meta-in-tech-sc pull request #6
Opened 2024-06-05 16:04 UTC by barsnick

The license is defined to "Dual BSD/GPL" in
https://github.com/8devices/qcacld-2.0/blob/CNSS.LEA.NRT_3.0/CORE/HDD/src/wlan_hdd_main.c#L20511
and
https://github.com/8devices/qcacld-2.0/blob/CNSS.LEA.NRT_3.0/CORE/SERVICES/HIF/USB/if_usb.c#L655.

It was explicitly changed in
https://github.com/8devices/qcacld-2.0/commit/1397cc135f39b1f4874fd3318bbc5dd6c3d9f412.

2024-06-06 13:58 UTC, mooraby requested changes
Does not build due to missing LIC_FILES_CHKSUM

2024-06-08 09:51 UTC, mhei approved these changes

2024-06-08 10:08 UTC, lategoodbye approved these changes

2024-06-10 09:22 UTC, mooraby approved these changes

2024-06-10 12:08 UTC, merged